# If there is a version to denote, set it here
about:
    contactEmail: O2Support@digitalglobe.com
    release: Hollywood
    releaseNumber: 2.4.1

# If there a page banner is needed, set it here
#banner:
#    backgroundColor: darkgray
#    description: This application is subject to change without notice.
#    enabled: true
#    text: BETA
#    textColor: white

# List any base layers that may be available
#baseLayers:
#    o2Mosaic:
#        layer: WorldGeographic
#        matrixSet: WorldGeographic
#        name: O2 Mosaic
#        projection: EPSG:4326
#        style: default
#        type: wmts
#        visible: true
#        url: ${baseUrl}/omar-wmts/wmts/getTile
#    osmBasic:
#        layers: o2-basemap-basic
#        name: OSM Basic
#        styles:
#        type: wms
#        url: ${baseUrl}/omar-mapproxy/service
#        visible: true
#    osmBright:
#        layers: o2-basemap-bright
#        name: OSM Bright
#        styles:
#        type: wms
#        visible: false
#        url: ${baseUrl}/omar-mapproxy/service

# Define the base URL to be used throughout the configuration
baseUrl: https://omar-dev.ossim.io

# If BEs are available, define the WFS query schema
#beLookup:
#    columnName: be_number
#    typeName: omar:facility
#    url: ${baseUrl}/omar-wfs/wfs

# If documentation is available, define the URL
#docsUrl: ${baseUrl}/omar-docs

# If the twofishes geocoder is available, define the URL
#geocoderUrl: ${baseUrl}/omar-ui/twoFishesProxy

# If ISA is available, define the URL
# Make sure the trailing forward slash is included
# Optional
#isaUrl: ${baseUrl}/isa-ui/

# List the various repository details
# You need at least one
#libraries:
#    o2-dev:
#        imageSpaceUrl: ${baseUrl}/omar-ui/omar/#/mapImage
#        kmlUrl: ${baseUrl}/omar-superoverlay/superOverlay/createKml
#        label: O2-DEV
#        layerType: wms
#        name: o2-dev
#        wfsUrl: ${baseUrl}/omar-wfs/wfs
#        wmsUrl: ${baseUrl}/omar-wms/wms
#    o2-rel:
#        imageSpaceUrl: https://omar-rel.ossim.io/omar-ui/omar/#/mapImage
#        kmlUrl: https://omar-rel.ossim.io/omar-superoverlay/superOverlay/createKml
#        label: O2-REL
#        layerType: wms
#        name: o2-rel
#        wfsUrl: https://omar-rel.ossim.io/omar-wfs/wfs
#        wmsUrl: https://omar-rel.ossim.io/omar-wms/wms

# Set the security classification banner here
securityClassificationBanner:
    backgroundColor: green
    classification: UNCLASSIFIED
    textColor: white

# Set the context path of the application
#server:
#    contextPath: /tlv

# If a terrain server is available, define the URL
#terrainProvider: //assets.agi.com/stk-terrain/world

# If access requires a PKI, define how to get the username here
#userInfo:
#    requestHeaderUserName: username
#    requestHeaderUserNameDefault: Anonymous

---
grails:
    profile: web
    codegen:
        defaultPackage: time_lapse
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: none
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
