about:
    release: Egmont Key
    releaseNumber: 2.1.0

# List any base layers that may be available
# Optional
#baseLayers:
#    osmBasic:
#        layers: o2-basemap-basic
#        name: OSM Basic
#        styles:
#        type: wms
#        url: ${baseUrl}/service-proxy/wmsProxy
#        visible: false
#    osmBright:
#        layers: o2-basemap-bright
#        name: OSM Bright
#        styles:
#        type: wms
#        visible: true
#        url: ${baseUrl}/service-proxy/wmsProxy

baseUrl: https://omar-dev.ossim.io

# If BEs are available, define the WFS query schema here
# Optional
#beLookup:
#    columnName: be_number
#    typeName: omar:facility
#    url: ${baseUrl}/omar-wfs/wfs

defaultLocation: 48.8584, 2.2945

# If documentation is available, define the URL
# Optional
#docsUrl: ${baseUrl}/omar-docs

# If the twofishes geocoder is available, define the URL
# Optional
#geocoderUrl: ${baseUrl}/omar-ui/twoFishesProxy

# If ISA is available, define the URL
# Make sure the trailing forward slash is included
# Optional
#isaUrl: ${baseUrl}/isa-ui/

# List the various repository details
# Required
#libraries:
#    o2-dev:
#        label: O2-DEV
#        layerType: wms
#        name: o2-dev
#        wfsUrl: ${baseUrl}/omar-wfs/wfs
#        wmsUrl: ${baseUrl}/omar-wms/wms
#    o2-rel:
#        label: O2-REL
#        layerType: wms
#        name: o2-rel
#        wfsUrl: https://omar-rel.ossim.io/omar-wfs/wfs
#        wmsUrl: https://omar-rel.ossim.io/omar-wms/wms

# Set the security classification banner here
# Required
securityClassification:
    backgroundColor: green
    text: UNCLASSIFIED
    textColor: white

# If a terrain server is available, define the URL
# Optional
#terrainProvider: //assets.agi.com/stk-terrain/world

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: time_lapse
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true


---
grails:
    resources:
        pattern: "/**"
